#cert manager with cloudflare dns provider
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: leoworths@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          email: leoworths@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: apiToken
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bankapp-certificate
  namespace: prod
spec:
  secretName: bankapp-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - worths.cloud
--- 
#ceritificate for vault
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-certificate
  namespace: vault
spec:
  secretName: vault-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: vault.worths.cloud
  dnsNames:
  - vault.worths.cloud