global:
  scrape_interval: 15s                
  evaluation_interval: 15s 

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - 'alert_rules.yaml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090'] # Replace with your Prometheus instance's IP or hostname

  - job_name: 'node_exporter' 
    static_configs:
    - targets: ['prometheus-node-exporter.monitoring.svc.cluster.local:9100'] # Replace with your Node Exporter's IP or hostname

  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
    - targets: ['localhost:8080'] # Replace with your Jenkins instance's IP or hostname

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://prometheus.io
        - https://worths.cloud 
        - https://vault.worths.cloud 
    dns_sd_configs:
      - names:
          - worths.cloud 
          - vault.worths.cloud 
        type: A
        port: 443
        refresh_interval: "30s"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115 #blackbox exporter address


# for hostnames
#   - job_name: 'blackbox'
    #   metrics_path: /probe
    #   params:
    #     module: [http_2xx]
    #   static_configs:
    #     - targets:
    #       - http://localhost:8080
    #       - https://example.com
    #       - 'localhost:9100'
    #   dns_sd_configs:
    #     - names:
    #         - example.com
    #       type: A
    #       port: 443
    #       refresh_interval: "30s"
    #   relabel_configs:
    #     - source_labels: [__address__]
    #       target_label: __param_target
    #     - source_labels: [__param_target]
    #       target_label: instance
    #     - target_label: __address__
    #       replacement: blackbox-exporter:9115 #blackbox exporter address

    # for ip addresses
    # - job_name: 'blackbox'
    #   metrics_path: /probe
    #   params:
    #     module: [http_2xx]
    #   static_configs:
    #     - targets:
    #       - http://localhost:8080
    #       - https://example.com
    #       - 'localhost:9100'
    #   relabel_configs:
    #     - source_labels: [__address__]
    #       target_label: __param_target
    #     - source_labels: [__param_target]
    #       target_label: instance
    #     - target_label: __address__
    #       replacement: blackbox-exporter:9115 #blackbox exporter address
