#storage class for EBS CSI driver
# This StorageClass uses the EBS CSI driver to provision persistent volumes in AWS.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-csi-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
  iops: "3000"  # Adjust to your desired IOPS, min 100
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

